name: Release my application
on: [push]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - 
        name: try to compile
        run: mvn compile
  ReleaseMyApp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - run: echo "..."
      - run: mvn package
      - run: ls -la target/
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "noter"
          body: my first release
          name: pre release of my application
